sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t dex1/react-test -f ./client/Dockerfile.dev ./client
  # can add more test here

script:
  - docker run CI=true dex1/react-test npm test -- --coverage
  # can add more script to run test here

after_success:
  - docker build -t dex1/multi-client ./client
  - docker build -t dex1/multi-nginx ./nginx
  - docker build -t dex1/multi-server ./server
  - docker build -t dex1/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dex1/multi-client
  - docker push dex1/multi-nginx
  - docker push dex1/multi-server
  - docker push dex1/multi-worker
