version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    # always running 100% of the time
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
  api:
    build:
      # we don't need to indecate the path like ./server/Dockerfile.dev
      # context will take care of it
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # inside the container don't try to override this folder
      # just leave it as is
      - /app/node_modules
      # look at everything in ./server and copy to /app
      # anytime our application tries ot access anything in app directory
      # inside of the container accept for the /node_modules above
      # it's going to essentailly get redirected back to the server directory
      # anytime we change in server we don't have to rebuild again
      - ./server:/app
    environment:
      # ALL OF THE BELOW ARE DEFAULT!
      - REDIS_HOST=redis
      # according to docker document of redis online we use this port
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
